// Generated by gencpp from file example_msg_srv/rotate_pointResponse.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINTRESPONSE_H
#define EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace example_msg_srv
{
template <class ContainerAllocator>
struct rotate_pointResponse_
{
  typedef rotate_pointResponse_<ContainerAllocator> Type;

  rotate_pointResponse_()
    : output_p()  {
    }
  rotate_pointResponse_(const ContainerAllocator& _alloc)
    : output_p(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _output_p_type;
  _output_p_type output_p;





  typedef boost::shared_ptr< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rotate_pointResponse_

typedef ::example_msg_srv::rotate_pointResponse_<std::allocator<void> > rotate_pointResponse;

typedef boost::shared_ptr< ::example_msg_srv::rotate_pointResponse > rotate_pointResponsePtr;
typedef boost::shared_ptr< ::example_msg_srv::rotate_pointResponse const> rotate_pointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace example_msg_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'example_msg_srv': ['/home/johann/catkin_ws/src/comp0127_lab/lab03_stack/example_msg_srv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ce3a576f2e4ff4b8335639b0058d366";
  }

  static const char* value(const ::example_msg_srv::rotate_pointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ce3a576f2e4ff4bULL;
  static const uint64_t static_value2 = 0x8335639b0058d366ULL;
};

template<class ContainerAllocator>
struct DataType< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_msg_srv/rotate_pointResponse";
  }

  static const char* value(const ::example_msg_srv::rotate_pointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point output_p\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::example_msg_srv::rotate_pointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rotate_pointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_msg_srv::rotate_pointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_msg_srv::rotate_pointResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.output_p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINTRESPONSE_H
