// Generated by gencpp from file example_msg_srv/rotate_point.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINT_H
#define EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINT_H

#include <ros/service_traits.h>


#include <example_msg_srv/rotate_pointRequest.h>
#include <example_msg_srv/rotate_pointResponse.h>


namespace example_msg_srv
{

struct rotate_point
{

typedef rotate_pointRequest Request;
typedef rotate_pointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rotate_point
} // namespace example_msg_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::example_msg_srv::rotate_point > {
  static const char* value()
  {
    return "2fb05bc22e36905ad98f9bce72e46ce8";
  }

  static const char* value(const ::example_msg_srv::rotate_point&) { return value(); }
};

template<>
struct DataType< ::example_msg_srv::rotate_point > {
  static const char* value()
  {
    return "example_msg_srv/rotate_point";
  }

  static const char* value(const ::example_msg_srv::rotate_point&) { return value(); }
};


// service_traits::MD5Sum< ::example_msg_srv::rotate_pointRequest> should match 
// service_traits::MD5Sum< ::example_msg_srv::rotate_point > 
template<>
struct MD5Sum< ::example_msg_srv::rotate_pointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::example_msg_srv::rotate_point >::value();
  }
  static const char* value(const ::example_msg_srv::rotate_pointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_msg_srv::rotate_pointRequest> should match 
// service_traits::DataType< ::example_msg_srv::rotate_point > 
template<>
struct DataType< ::example_msg_srv::rotate_pointRequest>
{
  static const char* value()
  {
    return DataType< ::example_msg_srv::rotate_point >::value();
  }
  static const char* value(const ::example_msg_srv::rotate_pointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::example_msg_srv::rotate_pointResponse> should match 
// service_traits::MD5Sum< ::example_msg_srv::rotate_point > 
template<>
struct MD5Sum< ::example_msg_srv::rotate_pointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::example_msg_srv::rotate_point >::value();
  }
  static const char* value(const ::example_msg_srv::rotate_pointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_msg_srv::rotate_pointResponse> should match 
// service_traits::DataType< ::example_msg_srv::rotate_point > 
template<>
struct DataType< ::example_msg_srv::rotate_pointResponse>
{
  static const char* value()
  {
    return DataType< ::example_msg_srv::rotate_point >::value();
  }
  static const char* value(const ::example_msg_srv::rotate_pointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAMPLE_MSG_SRV_MESSAGE_ROTATE_POINT_H
