// Generated by gencpp from file example_msg_srv/test_srvRequest.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVREQUEST_H
#define EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace example_msg_srv
{
template <class ContainerAllocator>
struct test_srvRequest_
{
  typedef test_srvRequest_<ContainerAllocator> Type;

  test_srvRequest_()
    : x()
    , y()
    , z()  {
    }
  test_srvRequest_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::example_msg_srv::test_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_msg_srv::test_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvRequest_

typedef ::example_msg_srv::test_srvRequest_<std::allocator<void> > test_srvRequest;

typedef boost::shared_ptr< ::example_msg_srv::test_srvRequest > test_srvRequestPtr;
typedef boost::shared_ptr< ::example_msg_srv::test_srvRequest const> test_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_msg_srv::test_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace example_msg_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'example_msg_srv': ['/home/johann/catkin_ws/src/comp0127_lab/lab03_stack/example_msg_srv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::test_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::test_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5166234939ddbad7844e2026f79c5fa";
  }

  static const char* value(const ::example_msg_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5166234939ddbadULL;
  static const uint64_t static_value2 = 0x7844e2026f79c5faULL;
};

template<class ContainerAllocator>
struct DataType< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_msg_srv/test_srvRequest";
  }

  static const char* value(const ::example_msg_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 x\n\
std_msgs/Float64 y\n\
std_msgs/Float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::example_msg_srv::test_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_msg_srv::test_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_msg_srv::test_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVREQUEST_H
