// Generated by gencpp from file example_msg_srv/test_srvResponse.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVRESPONSE_H
#define EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>

namespace example_msg_srv
{
template <class ContainerAllocator>
struct test_srvResponse_
{
  typedef test_srvResponse_<ContainerAllocator> Type;

  test_srvResponse_()
    : q()  {
    }
  test_srvResponse_(const ContainerAllocator& _alloc)
    : q(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _q_type;
  _q_type q;





  typedef boost::shared_ptr< ::example_msg_srv::test_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_msg_srv::test_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct test_srvResponse_

typedef ::example_msg_srv::test_srvResponse_<std::allocator<void> > test_srvResponse;

typedef boost::shared_ptr< ::example_msg_srv::test_srvResponse > test_srvResponsePtr;
typedef boost::shared_ptr< ::example_msg_srv::test_srvResponse const> test_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_msg_srv::test_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace example_msg_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'example_msg_srv': ['/home/johann/catkin_ws/src/comp0127_lab/lab03_stack/example_msg_srv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_msg_srv::test_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_msg_srv::test_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_msg_srv::test_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb310d1d9861005dc8b6d49680a2d86e";
  }

  static const char* value(const ::example_msg_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb310d1d9861005dULL;
  static const uint64_t static_value2 = 0xc8b6d49680a2d86eULL;
};

template<class ContainerAllocator>
struct DataType< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_msg_srv/test_srvResponse";
  }

  static const char* value(const ::example_msg_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion q\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::example_msg_srv::test_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_msg_srv::test_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_msg_srv::test_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.q);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_MSG_SRV_MESSAGE_TEST_SRVRESPONSE_H
