// Generated by gencpp from file example_msg_srv/test_srv.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MSG_SRV_MESSAGE_TEST_SRV_H
#define EXAMPLE_MSG_SRV_MESSAGE_TEST_SRV_H

#include <ros/service_traits.h>


#include <example_msg_srv/test_srvRequest.h>
#include <example_msg_srv/test_srvResponse.h>


namespace example_msg_srv
{

struct test_srv
{

typedef test_srvRequest Request;
typedef test_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_srv
} // namespace example_msg_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::example_msg_srv::test_srv > {
  static const char* value()
  {
    return "faec36214f3d0e984c1a2fa8299d68ca";
  }

  static const char* value(const ::example_msg_srv::test_srv&) { return value(); }
};

template<>
struct DataType< ::example_msg_srv::test_srv > {
  static const char* value()
  {
    return "example_msg_srv/test_srv";
  }

  static const char* value(const ::example_msg_srv::test_srv&) { return value(); }
};


// service_traits::MD5Sum< ::example_msg_srv::test_srvRequest> should match 
// service_traits::MD5Sum< ::example_msg_srv::test_srv > 
template<>
struct MD5Sum< ::example_msg_srv::test_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::example_msg_srv::test_srv >::value();
  }
  static const char* value(const ::example_msg_srv::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_msg_srv::test_srvRequest> should match 
// service_traits::DataType< ::example_msg_srv::test_srv > 
template<>
struct DataType< ::example_msg_srv::test_srvRequest>
{
  static const char* value()
  {
    return DataType< ::example_msg_srv::test_srv >::value();
  }
  static const char* value(const ::example_msg_srv::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::example_msg_srv::test_srvResponse> should match 
// service_traits::MD5Sum< ::example_msg_srv::test_srv > 
template<>
struct MD5Sum< ::example_msg_srv::test_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::example_msg_srv::test_srv >::value();
  }
  static const char* value(const ::example_msg_srv::test_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_msg_srv::test_srvResponse> should match 
// service_traits::DataType< ::example_msg_srv::test_srv > 
template<>
struct DataType< ::example_msg_srv::test_srvResponse>
{
  static const char* value()
  {
    return DataType< ::example_msg_srv::test_srv >::value();
  }
  static const char* value(const ::example_msg_srv::test_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAMPLE_MSG_SRV_MESSAGE_TEST_SRV_H
