(cl:defpackage cw1q5_srv-srv
  (:use )
  (:export
   "QUAT2ANGLEAXIS"
   "<QUAT2ANGLEAXIS-REQUEST>"
   "QUAT2ANGLEAXIS-REQUEST"
   "<QUAT2ANGLEAXIS-RESPONSE>"
   "QUAT2ANGLEAXIS-RESPONSE"
   "QUAT2ZYX"
   "<QUAT2ZYX-REQUEST>"
   "QUAT2ZYX-REQUEST"
   "<QUAT2ZYX-RESPONSE>"
   "QUAT2ZYX-RESPONSE"
   "ROTMAT2QUAT"
   "<ROTMAT2QUAT-REQUEST>"
   "ROTMAT2QUAT-REQUEST"
   "<ROTMAT2QUAT-RESPONSE>"
   "ROTMAT2QUAT-RESPONSE"
  ))

