# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sol_example_msg_srv/task_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class task_msg(genpy.Message):
  _md5sum = "9aa73411cfc8de91714b9efad534faa3"
  _type = "sol_example_msg_srv/task_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Float64 x
std_msgs/Float64 y
std_msgs/Float64 z
std_msgs/Float64 qw
std_msgs/Float64 qx
std_msgs/Float64 qy
std_msgs/Float64 qz
================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['x','y','z','qw','qx','qy','qz']
  _slot_types = ['std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,qw,qx,qy,qz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(task_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.z is None:
        self.z = std_msgs.msg.Float64()
      if self.qw is None:
        self.qw = std_msgs.msg.Float64()
      if self.qx is None:
        self.qx = std_msgs.msg.Float64()
      if self.qy is None:
        self.qy = std_msgs.msg.Float64()
      if self.qz is None:
        self.qz = std_msgs.msg.Float64()
    else:
      self.x = std_msgs.msg.Float64()
      self.y = std_msgs.msg.Float64()
      self.z = std_msgs.msg.Float64()
      self.qw = std_msgs.msg.Float64()
      self.qx = std_msgs.msg.Float64()
      self.qy = std_msgs.msg.Float64()
      self.qz = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.x.data, _x.y.data, _x.z.data, _x.qw.data, _x.qx.data, _x.qy.data, _x.qz.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.z is None:
        self.z = std_msgs.msg.Float64()
      if self.qw is None:
        self.qw = std_msgs.msg.Float64()
      if self.qx is None:
        self.qx = std_msgs.msg.Float64()
      if self.qy is None:
        self.qy = std_msgs.msg.Float64()
      if self.qz is None:
        self.qz = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x.data, _x.y.data, _x.z.data, _x.qw.data, _x.qx.data, _x.qy.data, _x.qz.data,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.x.data, _x.y.data, _x.z.data, _x.qw.data, _x.qx.data, _x.qy.data, _x.qz.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.z is None:
        self.z = std_msgs.msg.Float64()
      if self.qw is None:
        self.qw = std_msgs.msg.Float64()
      if self.qx is None:
        self.qx = std_msgs.msg.Float64()
      if self.qy is None:
        self.qy = std_msgs.msg.Float64()
      if self.qz is None:
        self.qz = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x.data, _x.y.data, _x.z.data, _x.qw.data, _x.qx.data, _x.qy.data, _x.qz.data,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
