# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sol_example_msg_srv/rotate_pointRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class rotate_pointRequest(genpy.Message):
  _md5sum = "aceea6d458663db9a7fb627bcdf34af2"
  _type = "sol_example_msg_srv/rotate_pointRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Quaternion q
geometry_msgs/Point input_p

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['q','input_p']
  _slot_types = ['geometry_msgs/Quaternion','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       q,input_p

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rotate_pointRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.input_p is None:
        self.input_p = geometry_msgs.msg.Point()
    else:
      self.q = geometry_msgs.msg.Quaternion()
      self.input_p = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.input_p.x, _x.input_p.y, _x.input_p.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.input_p is None:
        self.input_p = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.input_p.x, _x.input_p.y, _x.input_p.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.input_p.x, _x.input_p.y, _x.input_p.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.input_p is None:
        self.input_p = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.input_p.x, _x.input_p.y, _x.input_p.z,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sol_example_msg_srv/rotate_pointResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class rotate_pointResponse(genpy.Message):
  _md5sum = "2ce3a576f2e4ff4b8335639b0058d366"
  _type = "sol_example_msg_srv/rotate_pointResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point output_p


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['output_p']
  _slot_types = ['geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       output_p

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rotate_pointResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.output_p is None:
        self.output_p = geometry_msgs.msg.Point()
    else:
      self.output_p = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.output_p.x, _x.output_p.y, _x.output_p.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.output_p is None:
        self.output_p = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.output_p.x, _x.output_p.y, _x.output_p.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.output_p.x, _x.output_p.y, _x.output_p.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.output_p is None:
        self.output_p = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.output_p.x, _x.output_p.y, _x.output_p.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
class rotate_point(object):
  _type          = 'sol_example_msg_srv/rotate_point'
  _md5sum = '2fb05bc22e36905ad98f9bce72e46ce8'
  _request_class  = rotate_pointRequest
  _response_class = rotate_pointResponse
